---

- name: Load variables based on OS type
  ansible.builtin.include_tasks:
    file: vars.yml

- name: Install dovecot
  ansible.builtin.include_tasks:
    file: install.yml

- name: Configure dovecot
  ansible.builtin.include_tasks:
    file: config.yml
