---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    dovecot_ssl_key: "{{ openssl_server_key }}"
    dovecot_ssl_chain: "{{ openssl_server_crt }}"
    dovecot_domain: example.com
    postfix_ipv6: False
    postfix_domain: example.com
    postfix_fqdn: host.example.com
    postfix_ssl_key: "{{ openssl_server_key }}"
    postfix_ssl_chain: "{{ openssl_server_crt }}"
  pre_tasks:
    - name: Create 'remote_tmp'
      ansible.builtin.file:
        path: /root/.ansible/tmp
        state: directory
        mode: "0700"
  roles:
    - cron
    - openssl
    - postfix
  tasks:
    - name: Include role 'ansible-role-dovecot'
      ansible.builtin.include_role:
        name: ansible-role-dovecot
